name: Close milestone
description: Closes a given milestone by number

inputs:
  GITHUB_TOKEN:
    required: true
  RELEASE_TAG:
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Release
      shell: bash
      run: |
        gh release edit ${{ inputs.RELEASE_TAG}} --prerelease=false --latest
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
