
name: Deploy release to production

on:
  workflow_dispatch:

jobs:
  deploy_to_production:
    name: Deploy to production
    if: contains(github.ref, 'refs/heads/release')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deployment to production
        run: |
          echo "Deploying into production"
          echo "Deployment completed"

  publish_release:
    name: Publish the release
    runs-on: ubuntu-latest
    needs: [deploy_to_production]
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "tag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/release/}}" >> $GITHUB_OUTPUT
        id: extract-branch-name
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.github/actions/releases/update
        name: Publishing the release tag
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.extract-branch-name.outputs.tag }}
          