name: Feature branch workflow

on:
  push:
    branches:
      - '**'       
      - '!main'
      - '!release/**'

jobs:
  unit_tests:
    name: Unit tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          echo "Running unit tests"
          echo "Unit tests passed"

  integration_tests:
    name: Integration tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Integration tests
        run: |
          echo "Running integration tests"
          echo "Integration tests passed"

  sonarcloud_analysis:
    name: Static code analysis using SonarCloud
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Static code analysis using SonarCloud
        run: |
          echo "Running code analysis using SonarCloud"
          echo "Analysis passed"